all:
  hosts:
    node1:
      ansible_host: 158.160.20.51 # Хост
      ip: 10.10.2.7
    node2:
      ansible_host: 89.169.157.35
      ip: 10.10.1.10
    node3:
      ansible_host: 84.252.135.181
      ip: 10.10.3.28
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}